#!/usr/bin/bash

# function for removing lockfile
exit-ugreen-cputempmon() {
  if [[ -f "/var/run/ugreen-cputempmon.lock" ]]; then
    rm "/var/run/ugreen-cputempmon.lock"
  fi
}

# trap exit and remove lockfile
trap 'exit-ugreen-cputempmon' EXIT

# check if script is already running
if [[ -f "/var/run/ugreen-cputempmon.lock" ]]; then
  echo "ugreen-cputempmon already running!"
  exit 1
fi
touch /var/run/ugreen-cputempmon.lock

#{ lsmod | grep ledtrig_netdev > /dev/null; } || { modprobe -v ledtrig_netdev && sleep 2; }

# load environment variables
if [[ -f /etc/ugreen-leds.conf ]]; then
  source /etc/ugreen-leds.conf
fi

BRIGHTNESS_CPUTEMP_LED=${BRIGHTNESS_CPUTEMP_LED:="255"} 

COLOR_CPUTEMP_IDLE=${COLOR_CPUTEMP_IDLE:="0 128 0"} 
COLOR_CPUTEMP_LOW=${COLOR_CPUTEMP_LOW:="255 255 0"} 
COLOR_CPUTEMP_MID=${COLOR_CPUTEMP_MID:="255 165 0"}
COLOR_CPUTEMP_HIGH=${COLOR_CPUTEMP_HIGH:="255 0 0"} 

LIMIT_CPUTEMP_IDLE=${LIMIT_CPUTEMP_IDLE:=45} 
LIMIT_CPUTEMP_LOW=${LIMIT_CPUTEMP_LOW:=65} 
LIMIT_CPUTEMP_MID=${LIMIT_CPUTEMP_MID:=75}
LIMIT_CPUTEMP_HIGH=${LIMIT_CPUTEMP_HIGH:=90} 


led="power"
echo $COLOR_CPUTEMP_IDLE > /sys/class/leds/$led/color
echo $BRIGHTNESS_CPUTEMP_LED > /sys/class/leds/$led/brightness
echo none > /sys/class/leds/$led/blink_type

function set_cputemp_color() {
    
    CPU_TEMP=$(sensors 2>/dev/null | grep -oP -s 'Package.*?\+\K[0-9.]+')

        if [[ "$CPU_TEMP" > "$LIMIT_CPUTEMP_HIGH" ]]; then
           color=${COLOR_CPUTEMP_HIGH}
        elif [[ "$CPU_TEMP" > "$LIMIT_CPUTEMP_MID" ]]; then
           color=${COLOR_CPUTEMP_MID}
        elif [[ "$CPU_TEMP" > "$LIMIT_CPUTEMP_LOW" ]]; then
           color=${COLOR_CPUTEMP_LOW}
        else
           color=$COLOR_CPUTEMP_IDLE
        fi

    echo $color > /sys/class/leds/$led/color
}


while true; do

    set_cputemp_color

    sleep ${LED_REFRESH_INTERVAL}s

done
